### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by mlabonne** [KyujinHan/Sakura-SOLAR-DPO#1]
Hi, congrats and thanks a lot for sharing your code and hyperparameters!

I noticed a small typo in the code (https://github.com/KyujinHan/Sakura-SOLAR-DPO/blob/4d93e18904c82bc67c3fc24bf217de4159d602dd/DPO.py#L167): "Assitant" instead of "Assistant". It doesn't seem to be very important considering the performance of the model, but maybe something to fix for the next run.

**Comment by KyujinHan** [comment]
Thank you for your comment!

I fixed the typo right away!
Thank you for your interest in the code :)
